version: 2

models:
  - name: cleaned_transactions
    description: "Cleaned transaction data from raw ecommerce source"
    columns:
      - name: order_id
        description: "Unique order ID"
        test:
          - not_null
          - unique
        
      - name: order_date
        description: "Date the order was placed"
        tests:
          - not_null
  - name: daily_sales
    description: "Aggregated daily sales metrics by order date"
    columns:
      - name: order_date
        description: "The date of sales activity"
        tests:
          - not_null
      - name: total_orders
        description: "total number of orders placed that day"
      - name: total_items_sold
        description: "Total number of items sold that day"
      - name: total_sales
        description: "Total revenue from sales that day"

  - name: top_customers
    description: "Top 10 customers by total amount spent"
    columns:
      - name: customer_id
        description: "Customers ID"
        tests:
          - not_null
      - name: total_orders
        description: "Number of orders this customer placed"
      - name: total_spent
        description: "Total amount the customer spent"

  - name: top_products
    description: "Top 10 products ranked by quantity sold"
    columns:
      - name: product_id
        description: "Product ID"
        tests:
          - not_null
      - name: total_sold
        description: "Total units sold"
      - name: revenue
        description: "Total revenue generated by this product"
